# Generated by Django 4.1 on 2024-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityid', models.AutoField(primary_key=True, serialize=False)),
                ('activityname', models.CharField(max_length=50)),
            ],
        ),
    ]
