# Generated by Django 4.1 on 2024-02-21 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=20)),
                ('projectdesc', models.CharField(max_length=100)),
                ('projectdate', models.DateField(default=datetime.date.today)),
                ('projectcost', models.BigIntegerField()),
                ('startingdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
