# Generated by Django 4.1 on 2024-02-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
