# Generated by Django 4.1 on 2024-02-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='empid',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
