# Generated by Django 4.1 on 2024-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_employee_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startingdate',
            field=models.DateTimeField(),
        ),
    ]
