# Generated by Django 4.1 on 2024-02-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_project_enddate_alter_project_startingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startingdate',
            field=models.DateField(),
        ),
    ]
