# Generated by Django 4.1 on 2024-02-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('project_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.project')),
            ],
        ),
    ]
