# Generated by Django 4.1 on 2024-02-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_employee_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.team'),
        ),
    ]
