# Generated by Django 4.1 on 2024-02-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_employee_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
