# Generated by Django 4.1 on 2024-02-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_team_teamname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='team_id',
            new_name='teamid',
        ),
    ]
