# Generated by Django 4.1 on 2024-02-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_rename_team_id_employee_teamid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='project_id',
            new_name='projectid',
        ),
    ]
