# Generated by Django 4.1 on 2024-03-26 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='projectid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.project'),
        ),
    ]
