# Generated by Django 4.1 on 2024-04-11 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_remove_employee_status_employee_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigndate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
