# Generated by Django 4.1 on 2024-04-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_employee_assigndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
