# Generated by Django 4.1 on 2024-04-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projectid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.project'),
        ),
    ]
