# Generated by Django 4.1 on 2024-04-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0023_alter_employee_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teamid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.team'),
        ),
    ]
