# Generated by Django 4.1 on 2024-02-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0018_rename_project_id_team_projectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('projecttaskid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('startingdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('activityid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.activity')),
                ('projectid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.project')),
            ],
        ),
    ]
