# Generated by Django 4.1 on 2024-02-27 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_rename_project_id_team_projectid'),
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empassign',
            fields=[
                ('empassignid', models.AutoField(primary_key=True, serialize=False)),
                ('assigndate', models.DateField(default=datetime.date.today)),
                ('duedate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('empid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.employee')),
                ('projecttaskid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.projecttask')),
            ],
        ),
    ]
