# Generated by Django 4.1 on 2024-04-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_empassign_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='empassign',
            name='rstatus',
            field=models.CharField(default=12313, max_length=50),
            preserve_default=False,
        ),
    ]
