# Generated by Django 4.1 on 2024-04-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_empassign_rstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='status',
        ),
    ]
