# Generated by Django 4.1 on 2024-04-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_employee_assigndate'),
        ('ProjectManager', '0005_remove_projecttask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectassigndata',
            fields=[
                ('assignid', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.employee')),
                ('projectid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.project')),
            ],
        ),
    ]
