# Generated by Django 4.1 on 2024-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_projectassigndata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassigndata',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
